pluginManagement {
    includeBuild('ouisync-convention')
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
    }
}

rootProject.name = 'ouisync'

include 'ouisync-android'
include 'ouisync-service'
include 'ouisync-session'
include 'example'
