use anyhow::Result;
use heck::{AsLowerCamelCase, AsSnakeCase};
use ouisync_api_parser::{
    ComplexEnum, Context, Docs, EnumRepr, Fields, Item, RequestVariant, SimpleEnum, Struct,
    ToResponseVariantName, Type, Visibility,
};
use std::{
    fmt,
    io::{self, Write},
};

pub(crate) fn generate(ctx: &Context, out: &mut dyn Write) -> Result<()> {
    writeln!(out, "// Auto-generated by ouisync-bindgen. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import Foundation")?;
    writeln!(out)?;

    for (name, item) in &ctx.items {
        match item {
            Item::SimpleEnum(item) => {
                write_simple_enum(out, name, item)?;
                if name == "ErrorCode" {
                    write_error(out, item)?;
                }
            }
            Item::ComplexEnum(item) => write_complex_enum(out, name, item)?,
            Item::Struct(item) => write_struct(out, name, item)?,
        }
    }

    write_complex_enum(out, "Request", &ctx.request.to_enum())?;
    write_complex_enum(out, "Response", &ctx.response.to_enum())?;

    write_api_class(out, "Session", false, &ctx.request.variants)?;
    write_api_class(out, "Repository", true, &ctx.request.variants)?;
    write_api_class(out, "File", true, &ctx.request.variants)?;
    write_api_class(out, "NetworkSocket", true, &ctx.request.variants)?;
    write_api_class(out, "NetworkStream", true, &ctx.request.variants)?;

    writeln!(out, "public class UnexpectedResponse: Error {{}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_simple_enum(out: &mut dyn Write, name: &str, item: &SimpleEnum) -> Result<()> {
    let repr = match item.repr {
        EnumRepr::U8 => "UInt8",
        EnumRepr::U16 => "UInt16",
        EnumRepr::U32 => "UInt32",
        EnumRepr::U64 => "UInt64",
    };

    write_docs(out, "", &item.docs)?;
    writeln!(out, "public enum {name}: {repr} {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        writeln!(
            out,
            "{I}case {} = {}",
            AsLowerCamelCase(variant_name),
            variant.value
        )?;
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_complex_enum(out: &mut dyn Write, name: &str, item: &ComplexEnum) -> Result<()> {
    write_docs(out, "", &item.docs)?;

    match item.visibility {
        Visibility::Public => write!(out, "public ")?,
        Visibility::Private => write!(out, "internal ")?,
    }

    writeln!(out, "enum {name} {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        let case_name = format!("{}", AsLowerCamelCase(variant_name));

        match &variant.fields {
            Fields::Named(fields) => {
                write!(out, "{I}case {case_name}(")?;
                let mut first = true;
                for (field_name, field) in fields {
                    if !first {
                        write!(out, ", ")?;
                    }
                    write!(
                        out,
                        "{}: {}",
                        AsLowerCamelCase(field_name),
                        SwiftType(&field.ty)
                    )?;
                    first = false;
                }
                writeln!(out, ")")?;
            }
            Fields::Unnamed(field) => {
                writeln!(
                    out,
                    "{I}case {case_name}(_ value: {})",
                    SwiftType(&field.ty)
                )?;
            }
            Fields::Unit => {
                writeln!(out, "{I}case {case_name}")?;
            }
        }
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_struct(out: &mut dyn Write, name: &str, item: &Struct) -> Result<()> {
    write_docs(out, "", &item.docs)?;
    writeln!(out, "public struct {name} {{")?;

    match &item.fields {
        Fields::Named(fields) => {
            for (field_name, field) in fields {
                writeln!(
                    out,
                    "{I}public let {}: {}",
                    AsLowerCamelCase(field_name),
                    SwiftType(&field.ty),
                )?;
            }
        }
        Fields::Unnamed(field) => {
            writeln!(out, "{I}public let value: {}", SwiftType(&field.ty))?;
        }
        Fields::Unit => {}
    }

    if item.secret {
        writeln!(out)?;
        writeln!(
            out,
            "{I}public var debugDescription: String {{ \"\\(type(of: self))(******)\" }}"
        )?;
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_error(out: &mut dyn Write, item: &SimpleEnum) -> Result<()> {
    writeln!(out, "public class OuisyncError: Error {{")?;
    writeln!(out, "{I}public let code: ErrorCode")?;
    writeln!(out, "{I}public let message: String?")?;
    writeln!(out, "{I}public let sources: [String]")?;
    writeln!(out)?;
    writeln!(
        out,
        "{I}public init(_ code: ErrorCode, _ message: String? = nil, sources: [String] = []) {{"
    )?;
    writeln!(out, "{I}{I}self.code = code")?;
    writeln!(out, "{I}{I}self.message = message")?;
    writeln!(out, "{I}{I}self.sources = sources")?;
    writeln!(out, "{I}}}")?;

    for (variant_name, variant) in &item.variants {
        if variant_name == "Ok" || variant_name == "Other" {
            continue;
        }

        writeln!(out)?;
        write_docs(out, I, &variant.docs)?;
        writeln!(out, "{I}public class {variant_name}: OuisyncError {{")?;
        writeln!(
            out,
            "{I}{I}public init(_ message: String? = nil, sources: [String] = []) {{"
        )?;
        writeln!(
            out,
            "{I}{I}{I}super.init(.{}, message, sources: sources)",
            AsLowerCamelCase(variant_name)
        )?;
        writeln!(out, "{I}{I}}}")?;
        writeln!(out, "{I}}}")?;
    }

    writeln!(out)?;
    writeln!(
        out,
        "{I}public static func dispatch(_ code: ErrorCode, _ message: String? = nil, sources: [String] = []) -> OuisyncError {{"
    )?;
    writeln!(out, "{I}{I}switch code {{")?;

    for (variant_name, _) in &item.variants {
        if variant_name == "Ok" || variant_name == "Other" {
            continue;
        }
        writeln!(
            out,
            "{I}{I}case .{}: return {variant_name}(message, sources: sources)",
            AsLowerCamelCase(variant_name)
        )?;
    }

    writeln!(
        out,
        "{I}{I}default: return OuisyncError(code, message, sources: sources)"
    )?;
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;
    writeln!(out)?;
    writeln!(out, "{I}public var description: String {{")?;
    writeln!(
        out,
        "{I}{I}let all = ([message] + sources.map {{ Optional($0) }}).compactMap {{ $0 }}"
    )?;
    writeln!(
        out,
        "{I}{I}return \"\\(type(of: self)): \\(all.joined(separator: \" → \"))\""
    )?;
    writeln!(out, "{I}}}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_api_class(
    out: &mut dyn Write,
    name: &str,
    handle: bool,
    request_variants: &[(String, RequestVariant)],
) -> Result<()> {
    writeln!(out, "public class {name} {{")?;
    writeln!(out, "{I}internal let client: Client")?;

    if handle {
        writeln!(out, "{I}public let handle: {name}Handle")?;
        writeln!(out)?;
        writeln!(
            out,
            "{I}internal init(_ client: Client, _ handle: {name}Handle) {{"
        )?;
        writeln!(out, "{I}{I}self.client = client")?;
        writeln!(out, "{I}{I}self.handle = handle")?;
        writeln!(out, "{I}}}")?;
    } else {
        writeln!(out)?;
        writeln!(out, "{I}internal init(_ client: Client) {{")?;
        writeln!(out, "{I}{I}self.client = client")?;
        writeln!(out, "{I}}}")?;
    }

    let prefix = format!("{}_", AsSnakeCase(name));

    for (variant_name, variant) in request_variants {
        if variant.skip || variant.ret_stream_item.is_some() {
            continue;
        }

        let Some(op_name) = variant_name.strip_prefix(&prefix) else {
            continue;
        };

        let ret = match &variant.ret {
            Type::Result(ty, _) => ty.as_ref(),
            ty => ty,
        };
        let ret_stripped = ret.strip_suffix("Handle");
        let response_variant_name = ret.to_response_variant_name();
        let response_case = format!("{}", AsLowerCamelCase(&response_variant_name));

        let use_default_args = variant
            .fields
            .iter()
            .skip(if handle { 1 } else { 0 })
            .any(|(_, field)| SwiftType(&field.ty).default().is_none());

        writeln!(out)?;
        write_docs(out, I, &variant.docs)?;
        write!(out, "{I}public func {}(", AsLowerCamelCase(op_name))?;

        let mut first = true;
        for (index, (arg_name, field)) in variant.fields.iter().enumerate() {
            if index == 0 && handle {
                continue;
            }
            if !first {
                write!(out, ", ")?;
            }
            let param_name = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
            let ty = SwiftType(&field.ty);
            write!(out, "_ {param_name}: {ty}")?;
            if use_default_args {
                if let Some(default) = ty.default() {
                    write!(out, " = {default}")?;
                }
            }
            first = false;
        }

        write!(out, ") async throws")?;

        // Return type annotation
        match ret {
            Type::Unit => writeln!(out, " {{")?,
            _ => {
                // ret_stripped replaces Handle-suffixed types with their wrapper class.
                // SwiftType already renders Option<T> as "T?", so no extra "?" needed.
                let display = ret_stripped.as_ref().unwrap_or(ret);
                writeln!(out, " -> {} {{", SwiftType(display))?;
            }
        }

        // Build request
        let request_case = format!("{}", AsLowerCamelCase(variant_name));

        if variant.fields.is_empty() {
            writeln!(out, "{I}{I}let request = Request.{request_case}")?;
        } else {
            writeln!(out, "{I}{I}let request = Request.{request_case}(")?;
            for (index, (arg_name, _)) in variant.fields.iter().enumerate() {
                let arg = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
                if index == 0 && handle {
                    writeln!(out, "{I}{I}{I}handle,")?;
                } else {
                    writeln!(out, "{I}{I}{I}{arg},")?;
                }
            }
            writeln!(out, "{I}{I})")?;
        }

        writeln!(out, "{I}{I}let response = try await client.invoke(request)")?;
        writeln!(out, "{I}{I}switch response {{")?;

        match ret {
            Type::Unit => {
                // void return: server sends Response.unit
                writeln!(out, "{I}{I}case .unit:")?;
                writeln!(out, "{I}{I}{I}return")?;
            }
            Type::Option(_) => {
                // optional return: server sends .{responseCase}(value) or .none
                write!(out, "{I}{I}case .{response_case}(let value):")?;
                match &ret_stripped {
                    Some(Type::Option(w)) => writeln!(out, " return {w}(client, value)")?,
                    Some(_) => unreachable!(),
                    None => writeln!(out, " return value")?,
                }
                writeln!(out, "{I}{I}case .none:")?;
                writeln!(out, "{I}{I}{I}return nil")?;
            }
            _ => {
                write!(out, "{I}{I}case .{response_case}(let value):")?;
                match &ret_stripped {
                    Some(Type::Scalar(w)) => writeln!(out, " return {w}(client, value)")?,
                    Some(Type::Vec(w)) => {
                        writeln!(out, " return value.map {{ {w}(client, $0) }}")?
                    }
                    Some(Type::Map(_, w)) => {
                        writeln!(out, " return value.mapValues {{ {w}(client, $0) }}")?
                    }
                    Some(_) => unreachable!(),
                    None => writeln!(out, " return value")?,
                }
            }
        }

        writeln!(out, "{I}{I}default:")?;
        writeln!(out, "{I}{I}{I}throw UnexpectedResponse()")?;
        writeln!(out, "{I}{I}}}")?;
        writeln!(out, "{I}}}")?;
    }

    if handle {
        writeln!(out)?;
        writeln!(
            out,
            "{I}public static func == (lhs: {name}, rhs: {name}) -> Bool {{"
        )?;
        writeln!(out, "{I}{I}return lhs.handle == rhs.handle")?;
        writeln!(out, "{I}}}")?;
        writeln!(out)?;
        writeln!(
            out,
            "{I}public var description: String {{ \"\\(type(of: self))(\\(handle))\" }}"
        )?;
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_docs(out: &mut dyn Write, prefix: &str, docs: &Docs) -> io::Result<()> {
    for line in &docs.lines {
        writeln!(out, "{prefix}///{line}")?;
    }
    Ok(())
}

struct SwiftType<'a>(&'a Type);

impl SwiftType<'_> {
    fn default(&self) -> Option<&str> {
        match self.0 {
            Type::Option(_) => Some("nil"),
            Type::Scalar(s) if s == "bool" => Some("false"),
            _ => None,
        }
    }
}

impl fmt::Display for SwiftType<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Type::Unit => write!(f, "Void"),
            Type::Scalar(s) => write!(f, "{}", SwiftScalar(s)),
            Type::Option(s) => write!(f, "{}?", SwiftScalar(s)),
            Type::Vec(s) => write!(f, "[{}]", SwiftScalar(s)),
            Type::Map(k, v) => write!(f, "[{}: {}]", SwiftScalar(k), SwiftScalar(v)),
            Type::Bytes => write!(f, "Data"),
            Type::Result(..) => Err(fmt::Error),
        }
    }
}

struct SwiftScalar<'a>(&'a str);

impl fmt::Display for SwiftScalar<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            "u8" => write!(f, "UInt8"),
            "u16" => write!(f, "UInt16"),
            "u32" => write!(f, "UInt32"),
            "u64" | "usize" => write!(f, "UInt64"),
            "i8" => write!(f, "Int8"),
            "i16" => write!(f, "Int16"),
            "i32" => write!(f, "Int32"),
            "i64" | "isize" => write!(f, "Int64"),
            "bool" => write!(f, "Bool"),
            "PathBuf" | "PeerAddr" | "SocketAddr" | "String" => write!(f, "String"),
            "Duration" => write!(f, "TimeInterval"),
            "SystemTime" => write!(f, "Date"),
            "StateMonitor" => write!(f, "StateMonitorNode"),
            _ => write!(f, "{}", self.0),
        }
    }
}

const I: &str = "    ";
const DEFAULT_FIELD_NAME: &str = "value";
