use anyhow::Result;
use heck::{AsLowerCamelCase, AsSnakeCase, AsUpperCamelCase};
use ouisync_api_parser::{
    ComplexEnum, Context, Docs, Fields, Item, RequestVariant, SimpleEnum, Struct,
    ToResponseVariantName, Type, Visibility,
};
use std::{
    fmt,
    io::{self, Write},
};

pub(crate) fn generate(ctx: &Context, out: &mut dyn Write) -> Result<()> {
    writeln!(out, "// Auto-generated by ouisync-bindgen. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import Foundation")?;
    writeln!(out, "import MessagePack")?;
    writeln!(out)?;

    for (name, item) in &ctx.items {
        match item {
            Item::SimpleEnum(item) => {
                write_simple_enum(out, name, item)?;
                if name == "ErrorCode" {
                    write_error(out, item)?;
                }
            }
            Item::ComplexEnum(item) => write_complex_enum(out, name, item)?,
            Item::Struct(item) => write_struct(out, name, item)?,
        }
    }

    write_request_enum(out, &ctx.request.to_enum(), &ctx.request.variants)?;
    write_response_enum(out, &ctx.response.to_enum())?;

    write_api_class(out, "Session", false, &ctx.request.variants)?;
    write_api_class(out, "Repository", true, &ctx.request.variants)?;
    write_api_class(out, "File", true, &ctx.request.variants)?;
    write_api_class(out, "NetworkSocket", true, &ctx.request.variants)?;
    write_api_class(out, "NetworkStream", true, &ctx.request.variants)?;

    writeln!(out, "public class UnexpectedResponse: Error {{}}")?;
    writeln!(out)?;

    // Private msgpack helpers
    writeln!(out, "private func _msgpackInt(_ v: MessagePackValue) -> Int64? {{")?;
    writeln!(out, "{I}switch v {{ case .int(let n): return n; case .uint(let n): return Int64(bitPattern: n); default: return nil }}")?;
    writeln!(out, "}}")?;
    writeln!(out, "private func _msgpackUInt(_ v: MessagePackValue) -> UInt64? {{")?;
    writeln!(out, "{I}switch v {{ case .uint(let n): return n; case .int(let n): return UInt64(bitPattern: n); default: return nil }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_simple_enum(out: &mut dyn Write, name: &str, item: &SimpleEnum) -> Result<()> {
    let repr = enum_repr_str(&item.repr);

    write_docs(out, "", &item.docs)?;
    writeln!(out, "public enum {name}: {repr} {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        writeln!(
            out,
            "{I}case {} = {}",
            AsLowerCamelCase(variant_name),
            variant.value
        )?;
    }

    // Codec
    writeln!(out)?;
    writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{ .uint(UInt64(rawValue)) }}")?;
    writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
    writeln!(out, "{I}{I}guard let n = _msgpackUInt(v), let r = {repr}(exactly: n) else {{ return nil }}")?;
    writeln!(out, "{I}{I}return Self(rawValue: r)")?;
    writeln!(out, "{I}}}")?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn enum_repr_str(repr: &ouisync_api_parser::EnumRepr) -> &'static str {
    match repr {
        ouisync_api_parser::EnumRepr::U8 => "UInt8",
        ouisync_api_parser::EnumRepr::U16 => "UInt16",
        ouisync_api_parser::EnumRepr::U32 => "UInt32",
        ouisync_api_parser::EnumRepr::U64 => "UInt64",
    }
}

fn write_complex_enum(out: &mut dyn Write, name: &str, item: &ComplexEnum) -> Result<()> {
    write_docs(out, "", &item.docs)?;

    match item.visibility {
        Visibility::Public => write!(out, "public ")?,
        Visibility::Private => write!(out, "internal ")?,
    }

    writeln!(out, "enum {name} {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        let case_name = format!("{}", AsLowerCamelCase(variant_name));

        match &variant.fields {
            Fields::Named(fields) => {
                write!(out, "{I}case {case_name}(")?;
                let mut first = true;
                for (field_name, field) in fields {
                    if !first {
                        write!(out, ", ")?;
                    }
                    write!(
                        out,
                        "{}: {}",
                        AsLowerCamelCase(field_name),
                        SwiftType(&field.ty)
                    )?;
                    first = false;
                }
                writeln!(out, ")")?;
            }
            Fields::Unnamed(field) => {
                writeln!(
                    out,
                    "{I}case {case_name}(_ value: {})",
                    SwiftType(&field.ty)
                )?;
            }
            Fields::Unit => {
                writeln!(out, "{I}case {case_name}")?;
            }
        }
    }

    writeln!(out)?;
    // encode
    write_complex_enum_encode(out, item)?;
    writeln!(out)?;
    // decode
    write_complex_enum_decode(out, item)?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_complex_enum_encode(out: &mut dyn Write, item: &ComplexEnum) -> Result<()> {
    writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{")?;
    writeln!(out, "{I}{I}switch self {{")?;
    for (variant_name, variant) in &item.variants {
        let case_name = format!("{}", AsLowerCamelCase(variant_name));
        let msgpack_name = format!("{}", AsUpperCamelCase(variant_name));
        match &variant.fields {
            Fields::Unit => {
                writeln!(out, "{I}{I}case .{case_name}: return .string(\"{msgpack_name}\")")?;
            }
            Fields::Unnamed(field) => {
                let enc = encode_expr(&field.ty, "value");
                writeln!(out, "{I}{I}case .{case_name}(let value): return .map([.string(\"{msgpack_name}\"): {enc}])")?;
            }
            Fields::Named(fields) => {
                // Build pattern
                let pattern: Vec<String> = fields
                    .iter()
                    .map(|(n, _)| format!("let {}", AsLowerCamelCase(n)))
                    .collect();
                let pattern_str = pattern.join(", ");
                let enc_exprs: Vec<String> = fields
                    .iter()
                    .map(|(n, f)| encode_expr(&f.ty, &format!("{}", AsLowerCamelCase(n))))
                    .collect();
                let enc_arr = enc_exprs.join(", ");
                writeln!(out, "{I}{I}case .{case_name}({pattern_str}): return .map([.string(\"{msgpack_name}\"): .array([{enc_arr}])])")?;
            }
        }
    }
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;
    Ok(())
}

fn write_complex_enum_decode(out: &mut dyn Write, item: &ComplexEnum) -> Result<()> {
    writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
    writeln!(out, "{I}{I}switch v {{")?;

    // Unit variants via .string
    let has_unit = item.variants.iter().any(|(_, v)| matches!(v.fields, Fields::Unit));
    if has_unit {
        writeln!(out, "{I}{I}case .string(let name):")?;
        writeln!(out, "{I}{I}{I}switch name {{")?;
        for (variant_name, variant) in &item.variants {
            if matches!(variant.fields, Fields::Unit) {
                let case_name = format!("{}", AsLowerCamelCase(variant_name));
                let msgpack_name = format!("{}", AsUpperCamelCase(variant_name));
                writeln!(out, "{I}{I}{I}case \"{msgpack_name}\": return .{case_name}")?;
            }
        }
        writeln!(out, "{I}{I}{I}default: return nil")?;
        writeln!(out, "{I}{I}{I}}}")?;
    }

    // Non-unit variants via .map
    let has_non_unit = item.variants.iter().any(|(_, v)| !matches!(v.fields, Fields::Unit));
    if has_non_unit {
        writeln!(out, "{I}{I}case .map(let m) where m.count == 1:")?;
        writeln!(out, "{I}{I}{I}guard let entry = m.first, case .string(let name) = entry.key else {{ return nil }}")?;
        writeln!(out, "{I}{I}{I}switch name {{")?;
        for (variant_name, variant) in &item.variants {
            let case_name = format!("{}", AsLowerCamelCase(variant_name));
            let msgpack_name = format!("{}", AsUpperCamelCase(variant_name));
            match &variant.fields {
                Fields::Unit => {} // handled above
                Fields::Unnamed(field) => {
                    writeln!(out, "{I}{I}{I}case \"{msgpack_name}\":")?;
                    write_decode_stmts(out, &field.ty, "decoded", "entry.value", 4)?;
                    writeln!(out, "{I}{I}{I}{I}return .{case_name}(decoded)")?;
                }
                Fields::Named(fields) => {
                    writeln!(out, "{I}{I}{I}case \"{msgpack_name}\":")?;
                    writeln!(out, "{I}{I}{I}{I}guard case .array(let arr) = entry.value, arr.count == {} else {{ return nil }}", fields.len())?;
                    let mut args = Vec::new();
                    for (i, (field_name, field)) in fields.iter().enumerate() {
                        let fn_lcc = format!("{}", AsLowerCamelCase(field_name));
                        write_decode_stmts(out, &field.ty, &fn_lcc, &format!("arr[{i}]"), 4)?;
                        args.push(format!("{fn_lcc}: {fn_lcc}"));
                    }
                    writeln!(out, "{I}{I}{I}{I}return .{case_name}({})", args.join(", "))?;
                }
            }
        }
        writeln!(out, "{I}{I}{I}default: return nil")?;
        writeln!(out, "{I}{I}{I}}}")?;
    }

    writeln!(out, "{I}{I}default: return nil")?;
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;
    Ok(())
}

/// Writes decode guard statements for a given type. Produces:
///   guard let {varname} = ... else { return nil }
/// The `src` is the MessagePackValue expression.
fn write_decode_stmts(
    out: &mut dyn Write,
    ty: &Type,
    varname: &str,
    src: &str,
    indent: usize,
) -> Result<()> {
    let prefix = I.repeat(indent);
    match ty {
        Type::Unit => {
            writeln!(out, "{prefix}let {varname}: Void = ()")?;
        }
        Type::Scalar(s) => {
            if let Some(swift_decode) = scalar_decode_expr(s, src) {
                writeln!(out, "{prefix}guard let {varname} = {swift_decode} else {{ return nil }}")?;
            } else {
                // Custom type
                let t = SwiftScalar(s).to_string();
                writeln!(out, "{prefix}guard let {varname} = {t}.decodeFromMsgPack({src}) else {{ return nil }}")?;
            }
        }
        Type::Option(s) => {
            let t = SwiftScalar(s).to_string();
            writeln!(out, "{prefix}let {varname}: {t}?")?;
            writeln!(out, "{prefix}if case .nil = {src} {{")?;
            writeln!(out, "{prefix}{I}{varname} = nil")?;
            writeln!(out, "{prefix}}} else {{")?;
            // decode inner
            if let Some(inner_dec) = scalar_decode_expr(s, src) {
                writeln!(out, "{prefix}{I}guard let tmp_{varname} = {inner_dec} else {{ return nil }}")?;
                writeln!(out, "{prefix}{I}{varname} = tmp_{varname}")?;
            } else {
                writeln!(out, "{prefix}{I}guard let tmp_{varname} = {t}.decodeFromMsgPack({src}) else {{ return nil }}")?;
                writeln!(out, "{prefix}{I}{varname} = tmp_{varname}")?;
            }
            writeln!(out, "{prefix}}}")?;
        }
        Type::Vec(s) => {
            let elem_type = SwiftScalar(s).to_string();
            writeln!(out, "{prefix}guard case .array(let arr_{varname}) = {src} else {{ return nil }}")?;
            writeln!(out, "{prefix}var {varname}: [{elem_type}] = []")?;
            writeln!(out, "{prefix}for elem_{varname} in arr_{varname} {{")?;
            if let Some(inner_dec) = scalar_decode_expr(s, &format!("elem_{varname}")) {
                writeln!(out, "{prefix}{I}guard let x_{varname} = {inner_dec} else {{ return nil }}")?;
            } else {
                writeln!(out, "{prefix}{I}guard let x_{varname} = {elem_type}.decodeFromMsgPack(elem_{varname}) else {{ return nil }}")?;
            }
            writeln!(out, "{prefix}{I}{varname}.append(x_{varname})")?;
            writeln!(out, "{prefix}}}")?;
        }
        Type::Map(k, v) => {
            let k_swift = SwiftScalar(k).to_string();
            let v_swift = SwiftScalar(v).to_string();
            writeln!(out, "{prefix}guard case .map(let map_{varname}) = {src} else {{ return nil }}")?;
            writeln!(out, "{prefix}var {varname}: [{k_swift}: {v_swift}] = [:]")?;
            writeln!(out, "{prefix}for (mk, mv) in map_{varname} {{")?;
            // key decode
            if let Some(kd) = scalar_decode_expr(k, "mk") {
                writeln!(out, "{prefix}{I}guard let dk = {kd} else {{ return nil }}")?;
            } else {
                writeln!(out, "{prefix}{I}guard let dk = {k_swift}.decodeFromMsgPack(mk) else {{ return nil }}")?;
            }
            if let Some(vd) = scalar_decode_expr(v, "mv") {
                writeln!(out, "{prefix}{I}guard let dv = {vd} else {{ return nil }}")?;
            } else {
                writeln!(out, "{prefix}{I}guard let dv = {v_swift}.decodeFromMsgPack(mv) else {{ return nil }}")?;
            }
            writeln!(out, "{prefix}{I}{varname}[dk] = dv")?;
            writeln!(out, "{prefix}}}")?;
        }
        Type::Bytes => {
            writeln!(out, "{prefix}guard case .binary(let bytes_{varname}) = {src} else {{ return nil }}")?;
            writeln!(out, "{prefix}let {varname} = Data(bytes_{varname})")?;
        }
        Type::Result(..) => {
            writeln!(out, "{prefix}// Result not decoded inline")?;
        }
    }
    Ok(())
}

// Returns a Swift expression that decodes a scalar from a MessagePackValue,
// or None if this is a custom type that needs `.decodeFromMsgPack`.
fn scalar_decode_expr(s: &str, src: &str) -> Option<String> {
    match s {
        "u8" => Some(format!("(_msgpackUInt({src}).flatMap {{ UInt8(exactly: $0) }})")),
        "u16" => Some(format!("(_msgpackUInt({src}).flatMap {{ UInt16(exactly: $0) }})")),
        "u32" => Some(format!("(_msgpackUInt({src}).flatMap {{ UInt32(exactly: $0) }})")),
        "u64" | "usize" => Some(format!("_msgpackUInt({src})")),
        "i8" => Some(format!("(_msgpackInt({src}).flatMap {{ Int8(exactly: $0) }})")),
        "i16" => Some(format!("(_msgpackInt({src}).flatMap {{ Int16(exactly: $0) }})")),
        "i32" => Some(format!("(_msgpackInt({src}).flatMap {{ Int32(exactly: $0) }})")),
        "i64" | "isize" => Some(format!("_msgpackInt({src})")),
        "bool" => Some(format!("{{ if case .bool(let b) = {src} {{ return b }}; return nil }}()")),
        "String" | "PathBuf" | "PeerAddr" | "SocketAddr" => {
            Some(format!("{{ if case .string(let s) = {src} {{ return s }}; return nil }}()"))
        }
        "Duration" => Some(format!("(_msgpackInt({src}).map {{ TimeInterval($0) / 1000.0 }})")),
        "SystemTime" => Some(format!("(_msgpackInt({src}).map {{ Date(timeIntervalSince1970: TimeInterval($0) / 1000.0) }})")),
        _ => None, // custom type
    }
}

fn encode_expr(ty: &Type, expr: &str) -> String {
    match ty {
        Type::Unit => ".nil".to_string(),
        Type::Scalar(s) => encode_scalar_expr(s, expr),
        Type::Option(s) => {
            let inner = encode_scalar_expr(s, "x");
            format!("{{ if let x = {expr} {{ return {inner} }} else {{ return .nil }} }}()")
        }
        Type::Vec(s) => {
            let inner = encode_scalar_expr(s, "$0");
            format!(".array({expr}.map {{ {inner} }})")
        }
        Type::Map(k, v) => {
            let k_enc = encode_scalar_expr(k, "$0.key");
            let v_enc = encode_scalar_expr(v, "$0.value");
            format!(".map(Dictionary(uniqueKeysWithValues: {expr}.map {{ ({k_enc}, {v_enc}) }}))")
        }
        Type::Bytes => format!(".binary({expr})"),
        Type::Result(..) => ".nil".to_string(),
    }
}

fn encode_scalar_expr(s: &str, expr: &str) -> String {
    match s {
        "u8" | "u16" | "u32" | "u64" | "usize" => format!(".uint(UInt64({expr}))"),
        "i8" | "i16" | "i32" | "i64" | "isize" => format!(".int(Int64({expr}))"),
        "bool" => format!(".bool({expr})"),
        "String" | "PathBuf" | "PeerAddr" | "SocketAddr" => format!(".string({expr})"),
        "Duration" => format!(".int(Int64({expr} * 1000))"),
        "SystemTime" => format!(".int(Int64({expr}.timeIntervalSince1970 * 1000))"),
        _ => format!("{expr}.encodeToMsgPack()"),
    }
}

fn write_struct(out: &mut dyn Write, name: &str, item: &Struct) -> Result<()> {
    write_docs(out, "", &item.docs)?;
    writeln!(out, "public struct {} {{", swift_type_name(name))?;

    match &item.fields {
        Fields::Named(fields) => {
            for (field_name, field) in fields {
                writeln!(
                    out,
                    "{I}public let {}: {}",
                    AsLowerCamelCase(field_name),
                    SwiftType(&field.ty),
                )?;
            }
        }
        Fields::Unnamed(field) => {
            writeln!(out, "{I}public let value: {}", SwiftType(&field.ty))?;
        }
        Fields::Unit => {}
    }

    if item.secret {
        writeln!(out)?;
        writeln!(
            out,
            "{I}public var debugDescription: String {{ \"\\(type(of: self))(******)\" }}"
        )?;
    }

    writeln!(out)?;

    // Codec for struct
    match &item.fields {
        Fields::Unnamed(field) => {
            let enc = encode_expr(&field.ty, "value");
            writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{ {enc} }}")?;
            writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
            write_decode_stmts(out, &field.ty, "decoded", "v", 2)?;
            writeln!(out, "{I}{I}return Self(value: decoded)")?;
            writeln!(out, "{I}}}")?;
        }
        Fields::Named(fields) => {
            if fields.is_empty() {
                writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{ .array([]) }}")?;
                writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
                writeln!(out, "{I}{I}return Self()")?;
                writeln!(out, "{I}}}")?;
            } else {
                let enc_exprs: Vec<String> = fields
                    .iter()
                    .map(|(n, f)| encode_expr(&f.ty, &format!("{}", AsLowerCamelCase(n))))
                    .collect();
                let enc_arr = enc_exprs.join(", ");
                writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{")?;
                writeln!(out, "{I}{I}.array([{enc_arr}])")?;
                writeln!(out, "{I}}}")?;
                writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
                writeln!(out, "{I}{I}guard case .array(let arr) = v, arr.count == {} else {{ return nil }}", fields.len())?;
                let mut args = Vec::new();
                for (i, (field_name, field)) in fields.iter().enumerate() {
                    let fn_lcc = format!("{}", AsLowerCamelCase(field_name));
                    write_decode_stmts(out, &field.ty, &fn_lcc, &format!("arr[{i}]"), 2)?;
                    args.push(format!("{fn_lcc}: {fn_lcc}"));
                }
                writeln!(out, "{I}{I}return Self({})", args.join(", "))?;
                writeln!(out, "{I}}}")?;
            }
        }
        Fields::Unit => {
            writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{ .array([]) }}")?;
            writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Self? {{")?;
            writeln!(out, "{I}{I}return Self()")?;
            writeln!(out, "{I}}}")?;
        }
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_error(out: &mut dyn Write, item: &SimpleEnum) -> Result<()> {
    writeln!(out, "public class OuisyncError: Error {{")?;
    writeln!(out, "{I}public let code: ErrorCode")?;
    writeln!(out, "{I}public let message: String?")?;
    writeln!(out, "{I}public let sources: [String]")?;
    writeln!(out)?;
    writeln!(
        out,
        "{I}public init(_ code: ErrorCode, _ message: String? = nil, sources: [String] = []) {{"
    )?;
    writeln!(out, "{I}{I}self.code = code")?;
    writeln!(out, "{I}{I}self.message = message")?;
    writeln!(out, "{I}{I}self.sources = sources")?;
    writeln!(out, "{I}}}")?;

    for (variant_name, variant) in &item.variants {
        if variant_name == "Ok" || variant_name == "Other" {
            continue;
        }

        writeln!(out)?;
        write_docs(out, I, &variant.docs)?;
        writeln!(out, "{I}public class {variant_name}: OuisyncError {{")?;
        writeln!(
            out,
            "{I}{I}public init(_ message: String? = nil, sources: [String] = []) {{"
        )?;
        writeln!(
            out,
            "{I}{I}{I}super.init(.{}, message, sources: sources)",
            AsLowerCamelCase(variant_name)
        )?;
        writeln!(out, "{I}{I}}}")?;
        writeln!(out, "{I}}}")?;
    }

    writeln!(out)?;
    writeln!(
        out,
        "{I}public static func dispatch(_ code: ErrorCode, _ message: String? = nil, sources: [String] = []) -> OuisyncError {{"
    )?;
    writeln!(out, "{I}{I}switch code {{")?;

    for (variant_name, _) in &item.variants {
        if variant_name == "Ok" || variant_name == "Other" {
            continue;
        }
        writeln!(
            out,
            "{I}{I}case .{}: return {variant_name}(message, sources: sources)",
            AsLowerCamelCase(variant_name)
        )?;
    }

    writeln!(
        out,
        "{I}{I}default: return OuisyncError(code, message, sources: sources)"
    )?;
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;
    writeln!(out)?;
    writeln!(out, "{I}public var description: String {{")?;
    writeln!(
        out,
        "{I}{I}let all = ([message] + sources.map {{ Optional($0) }}).compactMap {{ $0 }}"
    )?;
    writeln!(
        out,
        "{I}{I}return \"\\(type(of: self)): \\(all.joined(separator: \" → \"))\""
    )?;
    writeln!(out, "{I}}}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

/// Write the Request enum with encode but no decode.
fn write_request_enum(
    out: &mut dyn Write,
    item: &ComplexEnum,
    _request_variants: &[(String, RequestVariant)],
) -> Result<()> {
    write_docs(out, "", &item.docs)?;

    writeln!(out, "internal enum Request {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        let case_name = format!("{}", AsLowerCamelCase(variant_name));

        match &variant.fields {
            Fields::Named(fields) => {
                write!(out, "{I}case {case_name}(")?;
                let mut first = true;
                for (field_name, field) in fields {
                    if !first {
                        write!(out, ", ")?;
                    }
                    write!(
                        out,
                        "_ {}: {}",
                        AsLowerCamelCase(field_name),
                        SwiftType(&field.ty)
                    )?;
                    first = false;
                }
                writeln!(out, ")")?;
            }
            Fields::Unnamed(field) => {
                writeln!(
                    out,
                    "{I}case {case_name}(_ value: {})",
                    SwiftType(&field.ty)
                )?;
            }
            Fields::Unit => {
                writeln!(out, "{I}case {case_name}")?;
            }
        }
    }

    writeln!(out)?;
    // Encode only for Request (no decode needed)
    writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{")?;
    writeln!(out, "{I}{I}switch self {{")?;
    // The request_variants have snake_case names; item.variants use PascalCase
    // We need to use the original snake_case names for AsUpperCamelCase
    // item.variants variant_name is PascalCase (from to_enum() which calls to_pascal_case())
    // But we need original snake_case for msgpack key.
    // Actually, AsUpperCamelCase on a PascalCase string gives the same PascalCase.
    for (variant_name, variant) in &item.variants {
        let case_name = format!("{}", AsLowerCamelCase(variant_name));
        // variant_name is PascalCase from to_enum(); AsUpperCamelCase on PascalCase = PascalCase
        let msgpack_name = variant_name.clone(); // already PascalCase
        match &variant.fields {
            Fields::Unit => {
                writeln!(out, "{I}{I}case .{case_name}: return .string(\"{msgpack_name}\")")?;
            }
            Fields::Unnamed(field) => {
                let enc = encode_expr(&field.ty, "value");
                writeln!(out, "{I}{I}case .{case_name}(let value): return .map([.string(\"{msgpack_name}\"): {enc}])")?;
            }
            Fields::Named(fields) => {
                let pattern: Vec<String> = fields
                    .iter()
                    .map(|(n, _)| format!("let {}", AsLowerCamelCase(n)))
                    .collect();
                let pattern_str = pattern.join(", ");
                let enc_exprs: Vec<String> = fields
                    .iter()
                    .map(|(n, f)| encode_expr(&f.ty, &format!("{}", AsLowerCamelCase(n))))
                    .collect();
                let enc_arr = enc_exprs.join(", ");
                writeln!(out, "{I}{I}case .{case_name}({pattern_str}): return .map([.string(\"{msgpack_name}\"): .array([{enc_arr}])])")?;
            }
        }
    }
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

/// Write the Response enum with encode and decode.
fn write_response_enum(out: &mut dyn Write, item: &ComplexEnum) -> Result<()> {
    writeln!(out, "internal enum Response {{")?;

    for (variant_name, variant) in &item.variants {
        write_docs(out, I, &variant.docs)?;
        let case_name = format!("{}", AsLowerCamelCase(variant_name));

        match &variant.fields {
            Fields::Named(fields) => {
                write!(out, "{I}case {case_name}(")?;
                let mut first = true;
                for (field_name, field) in fields {
                    if !first {
                        write!(out, ", ")?;
                    }
                    write!(
                        out,
                        "{}: {}",
                        AsLowerCamelCase(field_name),
                        SwiftType(&field.ty)
                    )?;
                    first = false;
                }
                writeln!(out, ")")?;
            }
            Fields::Unnamed(field) => {
                writeln!(
                    out,
                    "{I}case {case_name}(_ value: {})",
                    SwiftType(&field.ty)
                )?;
            }
            Fields::Unit => {
                writeln!(out, "{I}case {case_name}")?;
            }
        }
    }

    writeln!(out)?;

    // Encode
    writeln!(out, "{I}internal func encodeToMsgPack() -> MessagePackValue {{")?;
    writeln!(out, "{I}{I}switch self {{")?;
    for (variant_name, variant) in &item.variants {
        let case_name = format!("{}", AsLowerCamelCase(variant_name));
        let msgpack_name = variant_name.clone(); // PascalCase
        match &variant.fields {
            Fields::Unit => {
                writeln!(out, "{I}{I}case .{case_name}: return .string(\"{msgpack_name}\")")?;
            }
            Fields::Unnamed(field) => {
                let enc = encode_expr(&field.ty, "value");
                writeln!(out, "{I}{I}case .{case_name}(let value): return .map([.string(\"{msgpack_name}\"): {enc}])")?;
            }
            Fields::Named(fields) => {
                let pattern: Vec<String> = fields
                    .iter()
                    .map(|(n, _)| format!("let {}", AsLowerCamelCase(n)))
                    .collect();
                let pattern_str = pattern.join(", ");
                let enc_exprs: Vec<String> = fields
                    .iter()
                    .map(|(n, f)| encode_expr(&f.ty, &format!("{}", AsLowerCamelCase(n))))
                    .collect();
                let enc_arr = enc_exprs.join(", ");
                writeln!(out, "{I}{I}case .{case_name}({pattern_str}): return .map([.string(\"{msgpack_name}\"): .array([{enc_arr}])])")?;
            }
        }
    }
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;
    writeln!(out)?;

    // Decode
    writeln!(out, "{I}internal static func decodeFromMsgPack(_ v: MessagePackValue) -> Response? {{")?;
    writeln!(out, "{I}{I}switch v {{")?;

    // Unit variants
    let has_unit = item.variants.iter().any(|(_, v)| matches!(v.fields, Fields::Unit));
    if has_unit {
        writeln!(out, "{I}{I}case .string(let name):")?;
        writeln!(out, "{I}{I}{I}switch name {{")?;
        for (variant_name, variant) in &item.variants {
            if matches!(variant.fields, Fields::Unit) {
                let case_name = format!("{}", AsLowerCamelCase(variant_name));
                let msgpack_name = variant_name.clone();
                writeln!(out, "{I}{I}{I}case \"{msgpack_name}\": return .{case_name}")?;
            }
        }
        writeln!(out, "{I}{I}{I}default: return nil")?;
        writeln!(out, "{I}{I}{I}}}")?;
    }

    // Non-unit variants
    let has_non_unit = item.variants.iter().any(|(_, v)| !matches!(v.fields, Fields::Unit));
    if has_non_unit {
        writeln!(out, "{I}{I}case .map(let m) where m.count == 1:")?;
        writeln!(out, "{I}{I}{I}guard let entry = m.first, case .string(let name) = entry.key else {{ return nil }}")?;
        writeln!(out, "{I}{I}{I}switch name {{")?;
        for (variant_name, variant) in &item.variants {
            let case_name = format!("{}", AsLowerCamelCase(variant_name));
            let msgpack_name = variant_name.clone();
            match &variant.fields {
                Fields::Unit => {}
                Fields::Unnamed(field) => {
                    writeln!(out, "{I}{I}{I}case \"{msgpack_name}\":")?;
                    write_decode_stmts(out, &field.ty, "decoded", "entry.value", 4)?;
                    writeln!(out, "{I}{I}{I}{I}return .{case_name}(decoded)")?;
                }
                Fields::Named(fields) => {
                    writeln!(out, "{I}{I}{I}case \"{msgpack_name}\":")?;
                    writeln!(out, "{I}{I}{I}{I}guard case .array(let arr) = entry.value, arr.count == {} else {{ return nil }}", fields.len())?;
                    let mut args = Vec::new();
                    for (i, (field_name, field)) in fields.iter().enumerate() {
                        let fn_lcc = format!("{}", AsLowerCamelCase(field_name));
                        write_decode_stmts(out, &field.ty, &fn_lcc, &format!("arr[{i}]"), 4)?;
                        args.push(format!("{fn_lcc}: {fn_lcc}"));
                    }
                    writeln!(out, "{I}{I}{I}{I}return .{case_name}({})", args.join(", "))?;
                }
            }
        }
        writeln!(out, "{I}{I}{I}default: return nil")?;
        writeln!(out, "{I}{I}{I}}}")?;
    }

    writeln!(out, "{I}{I}default: return nil")?;
    writeln!(out, "{I}{I}}}")?;
    writeln!(out, "{I}}}")?;

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

fn write_api_class(
    out: &mut dyn Write,
    name: &str,
    handle: bool,
    request_variants: &[(String, RequestVariant)],
) -> Result<()> {
    writeln!(out, "public class {name} {{")?;
    writeln!(out, "{I}internal let client: Client")?;

    if handle {
        let handle_type_owned = format!("{name}Handle");
        let handle_type = swift_type_name(&handle_type_owned);
        writeln!(out, "{I}public let handle: {handle_type}")?;
        writeln!(out)?;
        writeln!(
            out,
            "{I}internal init(_ client: Client, _ handle: {handle_type}) {{"
        )?;
        writeln!(out, "{I}{I}self.client = client")?;
        writeln!(out, "{I}{I}self.handle = handle")?;
        writeln!(out, "{I}}}")?;
    } else {
        writeln!(out)?;
        writeln!(out, "{I}internal init(_ client: Client) {{")?;
        writeln!(out, "{I}{I}self.client = client")?;
        writeln!(out, "{I}}}")?;
    }

    let prefix = format!("{}_", AsSnakeCase(name));

    for (variant_name, variant) in request_variants {
        if variant.skip {
            continue;
        }

        let Some(op_name) = variant_name.strip_prefix(&prefix) else {
            continue;
        };

        if let Some(stream_item) = &variant.ret_stream_item {
            writeln!(out)?;
            write_docs(out, I, &variant.docs)?;
            write!(out, "{I}public func {}(", AsLowerCamelCase(op_name))?;

            let mut first = true;
            for (index, (arg_name, field)) in variant.fields.iter().enumerate() {
                if index == 0 && handle {
                    continue;
                }
                if !first {
                    write!(out, ", ")?;
                }
                let param_name = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
                write!(out, "_ {param_name}: {}", SwiftType(&field.ty))?;
                first = false;
            }

            writeln!(out, ") async throws -> AsyncStream<{}> {{", SwiftType(stream_item))?;

            let request_case = format!("{}", AsLowerCamelCase(variant_name));
            if variant.fields.is_empty() {
                writeln!(out, "{I}{I}let request = Request.{request_case}")?;
            } else {
                writeln!(out, "{I}{I}let request = Request.{request_case}(")?;
                for (index, (arg_name, _)) in variant.fields.iter().enumerate() {
                    let arg = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
                    if index == 0 && handle {
                        writeln!(out, "{I}{I}{I}handle,")?;
                    } else {
                        writeln!(out, "{I}{I}{I}{arg},")?;
                    }
                }
                writeln!(out, "{I}{I})")?;
            }

            writeln!(out, "{I}{I}let stream = try await client.subscribe(request)")?;
            writeln!(out, "{I}{I}return AsyncStream {{ continuation in")?;
            writeln!(out, "{I}{I}{I}let task = Task {{")?;
            writeln!(out, "{I}{I}{I}{I}for await response in stream {{")?;
            writeln!(out, "{I}{I}{I}{I}{I}switch response {{")?;

            match stream_item {
                Type::Unit => {
                    writeln!(out, "{I}{I}{I}{I}{I}case .unit: continuation.yield(())")?;
                }
                _ => {
                    let rv = stream_item.to_response_variant_name();
                    let rc = format!("{}", AsLowerCamelCase(&rv));
                    writeln!(
                        out,
                        "{I}{I}{I}{I}{I}case .{rc}(let value): continuation.yield(value)"
                    )?;
                }
            }

            writeln!(out, "{I}{I}{I}{I}{I}default: break")?;
            writeln!(out, "{I}{I}{I}{I}{I}}}")?;
            writeln!(out, "{I}{I}{I}{I}}}")?;
            writeln!(out, "{I}{I}{I}{I}continuation.finish()")?;
            writeln!(out, "{I}{I}{I}}}")?;
            writeln!(out, "{I}{I}{I}continuation.onTermination = {{ _ in task.cancel() }}")?;
            writeln!(out, "{I}{I}}}")?;
            writeln!(out, "{I}}}")?;
            continue;
        }

        let ret = match &variant.ret {
            Type::Result(ty, _) => ty.as_ref(),
            ty => ty,
        };
        let ret_stripped = ret.strip_suffix("Handle");
        let response_variant_name = ret.to_response_variant_name();
        let response_case = format!("{}", AsLowerCamelCase(&response_variant_name));

        let use_default_args = variant
            .fields
            .iter()
            .skip(if handle { 1 } else { 0 })
            .any(|(_, field)| SwiftType(&field.ty).default().is_none());

        writeln!(out)?;
        write_docs(out, I, &variant.docs)?;
        write!(out, "{I}public func {}(", AsLowerCamelCase(op_name))?;

        let mut first = true;
        for (index, (arg_name, field)) in variant.fields.iter().enumerate() {
            if index == 0 && handle {
                continue;
            }
            if !first {
                write!(out, ", ")?;
            }
            let param_name = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
            let ty = SwiftType(&field.ty);
            write!(out, "_ {param_name}: {ty}")?;
            if use_default_args {
                if let Some(default) = ty.default() {
                    write!(out, " = {default}")?;
                }
            }
            first = false;
        }

        write!(out, ") async throws")?;

        // Return type annotation
        match ret {
            Type::Unit => writeln!(out, " {{")?,
            _ => {
                // ret_stripped replaces Handle-suffixed types with their wrapper class.
                // SwiftType already renders Option<T> as "T?", so no extra "?" needed.
                let display = ret_stripped.as_ref().unwrap_or(ret);
                writeln!(out, " -> {} {{", SwiftType(display))?;
            }
        }

        // Build request
        let request_case = format!("{}", AsLowerCamelCase(variant_name));

        if variant.fields.is_empty() {
            writeln!(out, "{I}{I}let request = Request.{request_case}")?;
        } else {
            writeln!(out, "{I}{I}let request = Request.{request_case}(")?;
            for (index, (arg_name, _)) in variant.fields.iter().enumerate() {
                let arg = AsLowerCamelCase(arg_name.unwrap_or(DEFAULT_FIELD_NAME));
                if index == 0 && handle {
                    writeln!(out, "{I}{I}{I}handle,")?;
                } else {
                    writeln!(out, "{I}{I}{I}{arg},")?;
                }
            }
            writeln!(out, "{I}{I})")?;
        }

        writeln!(out, "{I}{I}let response = try await client.invoke(request)")?;
        writeln!(out, "{I}{I}switch response {{")?;

        match ret {
            Type::Unit => {
                // void return: server sends Response.unit
                writeln!(out, "{I}{I}case .unit:")?;
                writeln!(out, "{I}{I}{I}return")?;
            }
            Type::Option(_) => {
                // optional return: server sends .{responseCase}(value) or .none
                write!(out, "{I}{I}case .{response_case}(let value):")?;
                match &ret_stripped {
                    Some(Type::Option(w)) => writeln!(out, " return {w}(client, value)")?,
                    Some(_) => unreachable!(),
                    None => writeln!(out, " return value")?,
                }
                writeln!(out, "{I}{I}case .none:")?;
                writeln!(out, "{I}{I}{I}return nil")?;
            }
            _ => {
                write!(out, "{I}{I}case .{response_case}(let value):")?;
                match &ret_stripped {
                    Some(Type::Scalar(w)) => writeln!(out, " return {w}(client, value)")?,
                    Some(Type::Vec(w)) => {
                        writeln!(out, " return value.map {{ {w}(client, $0) }}")?
                    }
                    Some(Type::Map(_, w)) => {
                        writeln!(out, " return value.mapValues {{ {w}(client, $0) }}")?
                    }
                    Some(_) => unreachable!(),
                    None => writeln!(out, " return value")?,
                }
            }
        }

        writeln!(out, "{I}{I}default:")?;
        writeln!(out, "{I}{I}{I}throw UnexpectedResponse()")?;
        writeln!(out, "{I}{I}}}")?;
        writeln!(out, "{I}}}")?;
    }

    if handle {
        writeln!(out)?;
        writeln!(
            out,
            "{I}public static func == (lhs: {name}, rhs: {name}) -> Bool {{"
        )?;
        writeln!(out, "{I}{I}return lhs.handle.value == rhs.handle.value")?;
        writeln!(out, "{I}}}")?;
        writeln!(out)?;
        writeln!(
            out,
            "{I}public var description: String {{ \"\\(type(of: self))(\\(handle))\" }}"
        )?;
    }

    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

/// Renames Rust type names that conflict with Swift built-ins or Foundation types.
fn swift_type_name(name: &str) -> &str {
    match name {
        // Foundation already defines FileHandle for file descriptors.
        "FileHandle" => "OuisyncFileHandle",
        _ => name,
    }
}

fn write_docs(out: &mut dyn Write, prefix: &str, docs: &Docs) -> io::Result<()> {
    for line in &docs.lines {
        writeln!(out, "{prefix}///{line}")?;
    }
    Ok(())
}

struct SwiftType<'a>(&'a Type);

impl SwiftType<'_> {
    fn default(&self) -> Option<&str> {
        match self.0 {
            Type::Option(_) => Some("nil"),
            Type::Scalar(s) if s == "bool" => Some("false"),
            _ => None,
        }
    }
}

impl fmt::Display for SwiftType<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Type::Unit => write!(f, "Void"),
            Type::Scalar(s) => write!(f, "{}", SwiftScalar(s)),
            Type::Option(s) => write!(f, "{}?", SwiftScalar(s)),
            Type::Vec(s) => write!(f, "[{}]", SwiftScalar(s)),
            Type::Map(k, v) => write!(f, "[{}: {}]", SwiftScalar(k), SwiftScalar(v)),
            Type::Bytes => write!(f, "Data"),
            Type::Result(..) => Err(fmt::Error),
        }
    }
}

struct SwiftScalar<'a>(&'a str);

impl fmt::Display for SwiftScalar<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            "u8" => write!(f, "UInt8"),
            "u16" => write!(f, "UInt16"),
            "u32" => write!(f, "UInt32"),
            "u64" | "usize" => write!(f, "UInt64"),
            "i8" => write!(f, "Int8"),
            "i16" => write!(f, "Int16"),
            "i32" => write!(f, "Int32"),
            "i64" | "isize" => write!(f, "Int64"),
            "bool" => write!(f, "Bool"),
            "PathBuf" | "PeerAddr" | "SocketAddr" | "String" => write!(f, "String"),
            "Duration" => write!(f, "TimeInterval"),
            "SystemTime" => write!(f, "Date"),
            "StateMonitor" => write!(f, "StateMonitorNode"),
            _ => write!(f, "{}", swift_type_name(self.0)),
        }
    }
}

const I: &str = "    ";
const DEFAULT_FIELD_NAME: &str = "value";
